language: c
compiler:
  - gcc
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install autoconf
  - sudo apt-get install build-essential
  - sudo apt-get install gperf
  - sudo apt-get install libgd2-xpm-dev
  - sudo apt-get install fakeroot
  - sudo apt-get install devscripts
  - sudo apt-get install dh-make
  - sudo apt-get install asciidoc
  - sudo apt-get install chrpath
  - sudo apt-get install help2man
  - sudo apt-get install libicu-dev
  - sudo apt-get install apache2
script:
  - git config --global user.email "travis@localhost"
  - git config --global user.name "Travis Testuser"
  - ./configure    || exit 1
  - make           || exit 1
  - mkdir dist     || exit 1
  - make deb       || exit 1
notifications:
  irc:
    channels:
      - "chat.freenode.net#naemon-devel"
    on_success: change
    on_failure: always
    skip_join: true
